#!/bin/bash

set -e
set -u

script_directory=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
root_directory="$script_directory/.."
project=ISListViewAdapterSample

pushd "$root_directory/Sample" > /dev/null
echo "Updating CocoaPods..."
pod update --silent
xcodebuild -workspace "$project.xcworkspace" -scheme "$project" clean build | xcpretty -c
popd > /dev/null
